export { Dota2GSIServer } from './dota2/Dota2GSIServer';
export { BasicEvent } from './GSIServer';
export {
  Dota2GameState,
  Dota2Event,
  EventType,
  IAbility,
  IBuilding,
  IBuildings,
  IDota2State,
  IDota2StateEvent,
  IDota2ObserverState,
  IDota2ObserverStateEvent,
  IEvent,
  IHero,
  IItem,
  IItemContainer,
  IMap,
  IMapObserver,
  IPickBan,
  IPlayer,
  IPlayerKill,
  IPlayerObserver,
  IProvider,
  IWearbleItem,
  TeamType,
} from './dota2/interface';
